/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZimoliRouteImport } from './routes/zimoli'
import { Route as ServissRouteImport } from './routes/serviss'
import { Route as ParMumsRouteImport } from './routes/par-mums'
import { Route as KontaktiRouteImport } from './routes/kontakti'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProduktsSlugRouteImport } from './routes/produkts.$slug'
import { Route as KatalogsCategoryRouteImport } from './routes/katalogs.$category'
import { Route as BlogsSlugRouteImport } from './routes/blogs.$slug'

const ZimoliRoute = ZimoliRouteImport.update({
  id: '/zimoli',
  path: '/zimoli',
  getParentRoute: () => rootRouteImport,
} as any)
const ServissRoute = ServissRouteImport.update({
  id: '/serviss',
  path: '/serviss',
  getParentRoute: () => rootRouteImport,
} as any)
const ParMumsRoute = ParMumsRouteImport.update({
  id: '/par-mums',
  path: '/par-mums',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktiRoute = KontaktiRouteImport.update({
  id: '/kontakti',
  path: '/kontakti',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduktsSlugRoute = ProduktsSlugRouteImport.update({
  id: '/produkts/$slug',
  path: '/produkts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const KatalogsCategoryRoute = KatalogsCategoryRouteImport.update({
  id: '/katalogs/$category',
  path: '/katalogs/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsSlugRoute = BlogsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/kontakti': typeof KontaktiRoute
  '/par-mums': typeof ParMumsRoute
  '/serviss': typeof ServissRoute
  '/zimoli': typeof ZimoliRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/katalogs/$category': typeof KatalogsCategoryRoute
  '/produkts/$slug': typeof ProduktsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/kontakti': typeof KontaktiRoute
  '/par-mums': typeof ParMumsRoute
  '/serviss': typeof ServissRoute
  '/zimoli': typeof ZimoliRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/katalogs/$category': typeof KatalogsCategoryRoute
  '/produkts/$slug': typeof ProduktsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/kontakti': typeof KontaktiRoute
  '/par-mums': typeof ParMumsRoute
  '/serviss': typeof ServissRoute
  '/zimoli': typeof ZimoliRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/katalogs/$category': typeof KatalogsCategoryRoute
  '/produkts/$slug': typeof ProduktsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blogs'
    | '/kontakti'
    | '/par-mums'
    | '/serviss'
    | '/zimoli'
    | '/blogs/$slug'
    | '/katalogs/$category'
    | '/produkts/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blogs'
    | '/kontakti'
    | '/par-mums'
    | '/serviss'
    | '/zimoli'
    | '/blogs/$slug'
    | '/katalogs/$category'
    | '/produkts/$slug'
  id:
    | '__root__'
    | '/'
    | '/blogs'
    | '/kontakti'
    | '/par-mums'
    | '/serviss'
    | '/zimoli'
    | '/blogs/$slug'
    | '/katalogs/$category'
    | '/produkts/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogsRoute: typeof BlogsRouteWithChildren
  KontaktiRoute: typeof KontaktiRoute
  ParMumsRoute: typeof ParMumsRoute
  ServissRoute: typeof ServissRoute
  ZimoliRoute: typeof ZimoliRoute
  KatalogsCategoryRoute: typeof KatalogsCategoryRoute
  ProduktsSlugRoute: typeof ProduktsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zimoli': {
      id: '/zimoli'
      path: '/zimoli'
      fullPath: '/zimoli'
      preLoaderRoute: typeof ZimoliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/serviss': {
      id: '/serviss'
      path: '/serviss'
      fullPath: '/serviss'
      preLoaderRoute: typeof ServissRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/par-mums': {
      id: '/par-mums'
      path: '/par-mums'
      fullPath: '/par-mums'
      preLoaderRoute: typeof ParMumsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakti': {
      id: '/kontakti'
      path: '/kontakti'
      fullPath: '/kontakti'
      preLoaderRoute: typeof KontaktiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produkts/$slug': {
      id: '/produkts/$slug'
      path: '/produkts/$slug'
      fullPath: '/produkts/$slug'
      preLoaderRoute: typeof ProduktsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/katalogs/$category': {
      id: '/katalogs/$category'
      path: '/katalogs/$category'
      fullPath: '/katalogs/$category'
      preLoaderRoute: typeof KatalogsCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$slug': {
      id: '/blogs/$slug'
      path: '/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof BlogsSlugRouteImport
      parentRoute: typeof BlogsRoute
    }
  }
}

interface BlogsRouteChildren {
  BlogsSlugRoute: typeof BlogsSlugRoute
}

const BlogsRouteChildren: BlogsRouteChildren = {
  BlogsSlugRoute: BlogsSlugRoute,
}

const BlogsRouteWithChildren = BlogsRoute._addFileChildren(BlogsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogsRoute: BlogsRouteWithChildren,
  KontaktiRoute: KontaktiRoute,
  ParMumsRoute: ParMumsRoute,
  ServissRoute: ServissRoute,
  ZimoliRoute: ZimoliRoute,
  KatalogsCategoryRoute: KatalogsCategoryRoute,
  ProduktsSlugRoute: ProduktsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
