/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZimoliRouteImport } from './routes/zimoli'
import { Route as SikdatnesRouteImport } from './routes/sikdatnes'
import { Route as ServissRouteImport } from './routes/serviss'
import { Route as PrivatumaPolitikaRouteImport } from './routes/privatuma-politika'
import { Route as ParMumsRouteImport } from './routes/par-mums'
import { Route as KontaktiRouteImport } from './routes/kontakti'
import { Route as GdprRouteImport } from './routes/gdpr'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProduktsSlugRouteImport } from './routes/produkts.$slug'
import { Route as KatalogsCategoryRouteImport } from './routes/katalogs.$category'
import { Route as BlogsSlugRouteImport } from './routes/blogs.$slug'
import { Route as AdminLoginRouteImport } from './routes/admin.login'

const ZimoliRoute = ZimoliRouteImport.update({
  id: '/zimoli',
  path: '/zimoli',
  getParentRoute: () => rootRouteImport,
} as any)
const SikdatnesRoute = SikdatnesRouteImport.update({
  id: '/sikdatnes',
  path: '/sikdatnes',
  getParentRoute: () => rootRouteImport,
} as any)
const ServissRoute = ServissRouteImport.update({
  id: '/serviss',
  path: '/serviss',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivatumaPolitikaRoute = PrivatumaPolitikaRouteImport.update({
  id: '/privatuma-politika',
  path: '/privatuma-politika',
  getParentRoute: () => rootRouteImport,
} as any)
const ParMumsRoute = ParMumsRouteImport.update({
  id: '/par-mums',
  path: '/par-mums',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktiRoute = KontaktiRouteImport.update({
  id: '/kontakti',
  path: '/kontakti',
  getParentRoute: () => rootRouteImport,
} as any)
const GdprRoute = GdprRouteImport.update({
  id: '/gdpr',
  path: '/gdpr',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProduktsSlugRoute = ProduktsSlugRouteImport.update({
  id: '/produkts/$slug',
  path: '/produkts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const KatalogsCategoryRoute = KatalogsCategoryRouteImport.update({
  id: '/katalogs/$category',
  path: '/katalogs/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsSlugRoute = BlogsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogsRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blogs': typeof BlogsRouteWithChildren
  '/gdpr': typeof GdprRoute
  '/kontakti': typeof KontaktiRoute
  '/par-mums': typeof ParMumsRoute
  '/privatuma-politika': typeof PrivatumaPolitikaRoute
  '/serviss': typeof ServissRoute
  '/sikdatnes': typeof SikdatnesRoute
  '/zimoli': typeof ZimoliRoute
  '/admin/login': typeof AdminLoginRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/katalogs/$category': typeof KatalogsCategoryRoute
  '/produkts/$slug': typeof ProduktsSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/gdpr': typeof GdprRoute
  '/kontakti': typeof KontaktiRoute
  '/par-mums': typeof ParMumsRoute
  '/privatuma-politika': typeof PrivatumaPolitikaRoute
  '/serviss': typeof ServissRoute
  '/sikdatnes': typeof SikdatnesRoute
  '/zimoli': typeof ZimoliRoute
  '/admin/login': typeof AdminLoginRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/katalogs/$category': typeof KatalogsCategoryRoute
  '/produkts/$slug': typeof ProduktsSlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blogs': typeof BlogsRouteWithChildren
  '/gdpr': typeof GdprRoute
  '/kontakti': typeof KontaktiRoute
  '/par-mums': typeof ParMumsRoute
  '/privatuma-politika': typeof PrivatumaPolitikaRoute
  '/serviss': typeof ServissRoute
  '/sikdatnes': typeof SikdatnesRoute
  '/zimoli': typeof ZimoliRoute
  '/admin/login': typeof AdminLoginRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/katalogs/$category': typeof KatalogsCategoryRoute
  '/produkts/$slug': typeof ProduktsSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/blogs'
    | '/gdpr'
    | '/kontakti'
    | '/par-mums'
    | '/privatuma-politika'
    | '/serviss'
    | '/sikdatnes'
    | '/zimoli'
    | '/admin/login'
    | '/blogs/$slug'
    | '/katalogs/$category'
    | '/produkts/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blogs'
    | '/gdpr'
    | '/kontakti'
    | '/par-mums'
    | '/privatuma-politika'
    | '/serviss'
    | '/sikdatnes'
    | '/zimoli'
    | '/admin/login'
    | '/blogs/$slug'
    | '/katalogs/$category'
    | '/produkts/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/blogs'
    | '/gdpr'
    | '/kontakti'
    | '/par-mums'
    | '/privatuma-politika'
    | '/serviss'
    | '/sikdatnes'
    | '/zimoli'
    | '/admin/login'
    | '/blogs/$slug'
    | '/katalogs/$category'
    | '/produkts/$slug'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogsRoute: typeof BlogsRouteWithChildren
  GdprRoute: typeof GdprRoute
  KontaktiRoute: typeof KontaktiRoute
  ParMumsRoute: typeof ParMumsRoute
  PrivatumaPolitikaRoute: typeof PrivatumaPolitikaRoute
  ServissRoute: typeof ServissRoute
  SikdatnesRoute: typeof SikdatnesRoute
  ZimoliRoute: typeof ZimoliRoute
  KatalogsCategoryRoute: typeof KatalogsCategoryRoute
  ProduktsSlugRoute: typeof ProduktsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zimoli': {
      id: '/zimoli'
      path: '/zimoli'
      fullPath: '/zimoli'
      preLoaderRoute: typeof ZimoliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sikdatnes': {
      id: '/sikdatnes'
      path: '/sikdatnes'
      fullPath: '/sikdatnes'
      preLoaderRoute: typeof SikdatnesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/serviss': {
      id: '/serviss'
      path: '/serviss'
      fullPath: '/serviss'
      preLoaderRoute: typeof ServissRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privatuma-politika': {
      id: '/privatuma-politika'
      path: '/privatuma-politika'
      fullPath: '/privatuma-politika'
      preLoaderRoute: typeof PrivatumaPolitikaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/par-mums': {
      id: '/par-mums'
      path: '/par-mums'
      fullPath: '/par-mums'
      preLoaderRoute: typeof ParMumsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakti': {
      id: '/kontakti'
      path: '/kontakti'
      fullPath: '/kontakti'
      preLoaderRoute: typeof KontaktiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gdpr': {
      id: '/gdpr'
      path: '/gdpr'
      fullPath: '/gdpr'
      preLoaderRoute: typeof GdprRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/produkts/$slug': {
      id: '/produkts/$slug'
      path: '/produkts/$slug'
      fullPath: '/produkts/$slug'
      preLoaderRoute: typeof ProduktsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/katalogs/$category': {
      id: '/katalogs/$category'
      path: '/katalogs/$category'
      fullPath: '/katalogs/$category'
      preLoaderRoute: typeof KatalogsCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$slug': {
      id: '/blogs/$slug'
      path: '/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof BlogsSlugRouteImport
      parentRoute: typeof BlogsRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogsRouteChildren {
  BlogsSlugRoute: typeof BlogsSlugRoute
}

const BlogsRouteChildren: BlogsRouteChildren = {
  BlogsSlugRoute: BlogsSlugRoute,
}

const BlogsRouteWithChildren = BlogsRoute._addFileChildren(BlogsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogsRoute: BlogsRouteWithChildren,
  GdprRoute: GdprRoute,
  KontaktiRoute: KontaktiRoute,
  ParMumsRoute: ParMumsRoute,
  PrivatumaPolitikaRoute: PrivatumaPolitikaRoute,
  ServissRoute: ServissRoute,
  SikdatnesRoute: SikdatnesRoute,
  ZimoliRoute: ZimoliRoute,
  KatalogsCategoryRoute: KatalogsCategoryRoute,
  ProduktsSlugRoute: ProduktsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
